<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.15">
  <POU Name="SimpleSafetyProgram" Id="{451f3921-d055-4805-a882-c98f3c7f1b11}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM SimpleSafetyProgram
VAR

	fromTwinSafe_GroupInRun AT %I* : BOOL;
	fromTwinSafe_SafetyOK AT %I* : BOOL;
	fromTwinSafe_SafetyOKDelayed AT %I* : BOOL;
	
	toTwinSafe_ResetGroup AT %Q* : BOOL;
	toTwinSafe_StartGroup AT %Q* : BOOL;
	
	toTwinSafe_AlwaysON AT %Q* : BOOL;
	
	toTwinSafe_ResetSafetyProgram AT %Q* : BOOL;	

END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="SimpleSafetyProgram">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>